@startwbs WBS_もも肉の照り焼きをつくる
title WBS_もも肉の照り焼きをつくる
 

+[#White] もも肉の照り焼きをつくる
**[#Aqua] 肉を焼く
+++[#Yellow] フライパンを熱する 
+++[#Yellow] 肉を焼く

**[#Aqua] 照り焼きソースをつくる
+++[#Yellow] フライパンを熱する
+++[#Yellow] 調味料を混ぜる

**[#Aqua] 皿に盛る
+++[#Yellow] 皿に肉をのせる
+++[#Yellow] 照り焼きソースをかける
@endwbs
