@startwbs WBS_ポテトサラダをつくる
title WBS_ポテトサラダをつくる
 

+[#White] ポテトサラダを作る
**[#Aqua] 野菜を切る
+++[#Yellow] お湯を沸かす
+++[#Yellow] 野菜を切る
+++[#Yellow] 野菜を茹でる

**[#Aqua] 調味料と混ぜる
+++[#Yellow] 調味料を混ぜる
+++[#Yellow] 切った野菜に混ぜる

**[#Aqua] 皿に盛りつける
+++[#Yellow] 完成したポテサラを盛る
@endwbs
